In [1]:
import pandas as pd

In [2]:
with open("../data/metadata/GSE60424_series_matrix.txt", "r", encoding="utf-8") as f:
    for i in range(50):
        print(f.readline().strip())

!Series_title	"Next generation sequencing of human immune cell subsets across diseases"
!Series_geo_accession	"GSE60424"
!Series_status	"Public on Jan 06 2015"
!Series_submission_date	"Aug 14 2014"
!Series_last_update_date	"Jan 04 2024"
!Series_pubmed_id	"25314013"
!Series_summary	"This study compared whole transcriptome signatures of 6 immune cell subsets and whole blood from patients with an array of immune-associated diseases. Fresh blood samples were collected from healthy subjects and subjects diagnosed type 1 diabetes, amyotrophic lateral sclerosis, and sepsis, as well as multiple sclerosis patients before and 24 hours after the first treatment with IFN-beta. At the time of blood draw, an aliquot of whole blood was collected into a Tempus tube (Invitrogen), while the remainder of the primary fresh blood sample was processed to highly pure populations of neutrophils, monocytes, B cells, CD4 T cells, CD8 T cells, and natural killer cells. RNA was extracted from each of these cell subsets, as well as the whole blood samples, and processed into RNA sequencing (RNAseq) libraries (Illumina TruSeq). Sequencing libraries were analyzed on an Illumina HiScan, with a target read depth of ~20M reads. Reads were demultiplexed, mapped to human gene models (ENSEMBL), and tabulated using HTSeq. Read count data were normalized by the TMM procedure (edgeR package)."
!Series_overall_design	"We performed whole genome RNAseq profiling of immune cell subsets and whole blood from subjects with an array of immune-associated diseases."
!Series_type	"Expression profiling by high throughput sequencing"
!Series_contributor	"Cate,,Speake"
!Series_contributor	"Peter,S,Linsley"
!Series_contributor	"Elizabeth,,Whalen"
!Series_contributor	"Damien,,Chaussabel"
!Series_contributor	"Scott,R,Presnell"
!Series_contributor	"Michael,J,Mason"
!Series_contributor	"Vivian,H,Gersuk"
!Series_contributor	"Kimm,K,O'Brien"
!Series_contributor	"Quynh-Anh,,Nguyen"
!Series_contributor	"Carla,J,Greenbaum"
!Series_contributor	"Jane,H,Buckner"
!Series_contributor	"Uma,,Malhotra"
!Series_sample_id	"GSM1479433 GSM1479434 GSM1479435 GSM1479436 GSM1479437 GSM1479438 GSM1479439 GSM1479440 GSM1479441 GSM1479442 GSM1479443 GSM1479444 GSM1479445 GSM1479446 GSM1479447 GSM1479448 GSM1479449 GSM1479450 GSM1479451 GSM1479452 GSM1479453 GSM1479454 GSM1479455 GSM1479456 GSM1479457 GSM1479458 GSM1479459 GSM1479460 GSM1479461 GSM1479462 GSM1479463 GSM1479464 GSM1479465 GSM1479466 GSM1479467 GSM1479468 GSM1479469 GSM1479470 GSM1479471 GSM1479472 GSM1479473 GSM1479474 GSM1479475 GSM1479476 GSM1479477 GSM1479478 GSM1479479 GSM1479480 GSM1479481 GSM1479482 GSM1479483 GSM1479484 GSM1479485 GSM1479486 GSM1479487 GSM1479488 GSM1479489 GSM1479490 GSM1479491 GSM1479492 GSM1479493 GSM1479494 GSM1479495 GSM1479496 GSM1479497 GSM1479498 GSM1479499 GSM1479500 GSM1479501 GSM1479502 GSM1479503 GSM1479504 GSM1479505 GSM1479506 GSM1479507 GSM1479508 GSM1479509 GSM1479510 GSM1479511 GSM1479512 GSM1479513 GSM1479514 GSM1479515 GSM1479516 GSM1479517 GSM1479518 GSM1479519 GSM1479520 GSM1479521 GSM1479522 GSM1479523 GSM1479524 GSM1479525 GSM1479526 GSM1479527 GSM1479528 GSM1479529 GSM1479530 GSM1479531 GSM1479532 GSM1479533 GSM1479534 GSM1479535 GSM1479536 GSM1479537 GSM1479538 GSM1479539 GSM1479540 GSM1479541 GSM1479542 GSM1479543 GSM1479544 GSM1479545 GSM1479546 GSM1479547 GSM1479548 GSM1479549 GSM1479550 GSM1479551 GSM1479552 GSM1479553 GSM1479554 GSM1479555 GSM1479556 GSM1479557 GSM1479558 GSM1479559 GSM1479560 GSM1479561 GSM1479562 GSM1479563 GSM1479564 GSM1479565 GSM1479566 "
!Series_contact_name	"Stephanie,,Osmond"
!Series_contact_email	"sosmond@benaroyaresearch.org"
!Series_contact_institute	"Benaroya Research Institute"
!Series_contact_address	"1201 9th Ave"
!Series_contact_city	"Seattle,"
!Series_contact_state	"WA"
!Series_contact_zip/postal_code	"98101"
!Series_contact_country	"USA"
!Series_supplementary_file	"ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE60nnn/GSE60424/suppl/GSE60424_GEOSubmit_FC1to11_normalized_counts.txt.gz"
!Series_platform_id	"GPL15456"
!Series_platform_taxid	"9606"
!Series_sample_taxid	"9606"
!Series_relation	"BioProject: https://www.ncbi.nlm.nih.gov/bioproject/PRJNA258216"
!Series_relation	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRP045500"

!Sample_title	"lib221"	"lib222"	"lib223"	"lib224"	"lib225"	"lib226"	"lib227"	"lib228"	"lib229"	"lib230"	"lib231"	"lib232"	"lib233"	"lib234"	"lib235"	"lib236"	"lib237"	"lib238"	"lib239"	"lib240"	"lib241"	"lib242"	"lib243"	"lib244"	"lib245"	"lib246"	"lib247"	"lib248"	"lib249"	"lib250"	"lib251"	"lib252"	"lib253"	"lib254"	"lib255"	"lib256"	"lib257"	"lib258"	"lib259"	"lib260"	"lib261"	"lib262"	"lib263"	"lib264"	"lib265"	"lib266"	"lib267"	"lib268"	"lib269"	"lib270"	"lib271"	"lib272"	"lib273"	"lib274"	"lib275"	"lib276"	"lib277"	"lib278"	"lib279"	"lib280"	"lib281"	"lib282"	"lib283"	"lib284"	"lib285"	"lib286"	"lib288"	"lib289"	"lib290"	"lib291"	"lib292"	"lib293"	"lib294"	"lib295"	"lib296"	"lib297"	"lib298"	"lib299"	"lib300"	"lib301"	"lib302"	"lib303"	"lib304"	"lib305"	"lib306"	"lib307"	"lib308"	"lib309"	"lib310"	"lib311"	"lib312"	"lib313"	"lib314"	"lib315"	"lib316"	"lib317"	"lib318"	"lib319"	"lib320"	"lib321"	"lib322"	"lib323"	"lib324"	"lib325"	"lib326"	"lib327"	"lib328"	"lib329"	"lib330"	"lib331"	"lib332"	"lib333"	"lib334"	"lib335"	"lib336"	"lib337"	"lib338"	"lib339"	"lib340"	"lib341"	"lib342"	"lib343"	"lib344"	"lib345"	"lib346"	"lib347"	"lib348"	"lib349"	"lib350"	"lib351"	"lib352"	"lib353"	"lib354"	"lib355"
!Sample_geo_accession	"GSM1479433"	"GSM1479434"	"GSM1479435"	"GSM1479436"	"GSM1479437"	"GSM1479438"	"GSM1479439"	"GSM1479440"	"GSM1479441"	"GSM1479442"	"GSM1479443"	"GSM1479444"	"GSM1479445"	"GSM1479446"	"GSM1479447"	"GSM1479448"	"GSM1479449"	"GSM1479450"	"GSM1479451"	"GSM1479452"	"GSM1479453"	"GSM1479454"	"GSM1479455"	"GSM1479456"	"GSM1479457"	"GSM1479458"	"GSM1479459"	"GSM1479460"	"GSM1479461"	"GSM1479462"	"GSM1479463"	"GSM1479464"	"GSM1479465"	"GSM1479466"	"GSM1479467"	"GSM1479468"	"GSM1479469"	"GSM1479470"	"GSM1479471"	"GSM1479472"	"GSM1479473"	"GSM1479474"	"GSM1479475"	"GSM1479476"	"GSM1479477"	"GSM1479478"	"GSM1479479"	"GSM1479480"	"GSM1479481"	"GSM1479482"	"GSM1479483"	"GSM1479484"	"GSM1479485"	"GSM1479486"	"GSM1479487"	"GSM1479488"	"GSM1479489"	"GSM1479490"	"GSM1479491"	"GSM1479492"	"GSM1479493"	"GSM1479494"	"GSM1479495"	"GSM1479496"	"GSM1479497"	"GSM1479498"	"GSM1479499"	"GSM1479500"	"GSM1479501"	"GSM1479502"	"GSM1479503"	"GSM1479504"	"GSM1479505"	"GSM1479506"	"GSM1479507"	"GSM1479508"	"GSM1479509"	"GSM1479510"	"GSM1479511"	"GSM1479512"	"GSM1479513"	"GSM1479514"	"GSM1479515"	"GSM1479516"	"GSM1479517"	"GSM1479518"	"GSM1479519"	"GSM1479520"	"GSM1479521"	"GSM1479522"	"GSM1479523"	"GSM1479524"	"GSM1479525"	"GSM1479526"	"GSM1479527"	"GSM1479528"	"GSM1479529"	"GSM1479530"	"GSM1479531"	"GSM1479532"	"GSM1479533"	"GSM1479534"	"GSM1479535"	"GSM1479536"	"GSM1479537"	"GSM1479538"	"GSM1479539"	"GSM1479540"	"GSM1479541"	"GSM1479542"	"GSM1479543"	"GSM1479544"	"GSM1479545"	"GSM1479546"	"GSM1479547"	"GSM1479548"	"GSM1479549"	"GSM1479550"	"GSM1479551"	"GSM1479552"	"GSM1479553"	"GSM1479554"	"GSM1479555"	"GSM1479556"	"GSM1479557"	"GSM1479558"	"GSM1479559"	"GSM1479560"	"GSM1479561"	"GSM1479562"	"GSM1479563"	"GSM1479564"	"GSM1479565"	"GSM1479566"
!Sample_status	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"
!Sample_submission_date	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"
!Sample_last_update_date	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"
!Sample_type	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"
!Sample_channel_count	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"
!Sample_source_name_ch1	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"
!Sample_organism_ch1	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"

In [3]:
with open("../data/metadata/GSE60424_series_matrix.txt", "r", encoding="utf-8") as f:
    for i in range(60):
        print(f"{i+1}: {f.readline().strip()}")

1: !Series_title	"Next generation sequencing of human immune cell subsets across diseases"
2: !Series_geo_accession	"GSE60424"
3: !Series_status	"Public on Jan 06 2015"
4: !Series_submission_date	"Aug 14 2014"
5: !Series_last_update_date	"Jan 04 2024"
6: !Series_pubmed_id	"25314013"
7: !Series_summary	"This study compared whole transcriptome signatures of 6 immune cell subsets and whole blood from patients with an array of immune-associated diseases. Fresh blood samples were collected from healthy subjects and subjects diagnosed type 1 diabetes, amyotrophic lateral sclerosis, and sepsis, as well as multiple sclerosis patients before and 24 hours after the first treatment with IFN-beta. At the time of blood draw, an aliquot of whole blood was collected into a Tempus tube (Invitrogen), while the remainder of the primary fresh blood sample was processed to highly pure populations of neutrophils, monocytes, B cells, CD4 T cells, CD8 T cells, and natural killer cells. RNA was extracted from each of these cell subsets, as well as the whole blood samples, and processed into RNA sequencing (RNAseq) libraries (Illumina TruSeq). Sequencing libraries were analyzed on an Illumina HiScan, with a target read depth of ~20M reads. Reads were demultiplexed, mapped to human gene models (ENSEMBL), and tabulated using HTSeq. Read count data were normalized by the TMM procedure (edgeR package)."
8: !Series_overall_design	"We performed whole genome RNAseq profiling of immune cell subsets and whole blood from subjects with an array of immune-associated diseases."
9: !Series_type	"Expression profiling by high throughput sequencing"
10: !Series_contributor	"Cate,,Speake"
11: !Series_contributor	"Peter,S,Linsley"
12: !Series_contributor	"Elizabeth,,Whalen"
13: !Series_contributor	"Damien,,Chaussabel"
14: !Series_contributor	"Scott,R,Presnell"
15: !Series_contributor	"Michael,J,Mason"
16: !Series_contributor	"Vivian,H,Gersuk"
17: !Series_contributor	"Kimm,K,O'Brien"
18: !Series_contributor	"Quynh-Anh,,Nguyen"
19: !Series_contributor	"Carla,J,Greenbaum"
20: !Series_contributor	"Jane,H,Buckner"
21: !Series_contributor	"Uma,,Malhotra"
22: !Series_sample_id	"GSM1479433 GSM1479434 GSM1479435 GSM1479436 GSM1479437 GSM1479438 GSM1479439 GSM1479440 GSM1479441 GSM1479442 GSM1479443 GSM1479444 GSM1479445 GSM1479446 GSM1479447 GSM1479448 GSM1479449 GSM1479450 GSM1479451 GSM1479452 GSM1479453 GSM1479454 GSM1479455 GSM1479456 GSM1479457 GSM1479458 GSM1479459 GSM1479460 GSM1479461 GSM1479462 GSM1479463 GSM1479464 GSM1479465 GSM1479466 GSM1479467 GSM1479468 GSM1479469 GSM1479470 GSM1479471 GSM1479472 GSM1479473 GSM1479474 GSM1479475 GSM1479476 GSM1479477 GSM1479478 GSM1479479 GSM1479480 GSM1479481 GSM1479482 GSM1479483 GSM1479484 GSM1479485 GSM1479486 GSM1479487 GSM1479488 GSM1479489 GSM1479490 GSM1479491 GSM1479492 GSM1479493 GSM1479494 GSM1479495 GSM1479496 GSM1479497 GSM1479498 GSM1479499 GSM1479500 GSM1479501 GSM1479502 GSM1479503 GSM1479504 GSM1479505 GSM1479506 GSM1479507 GSM1479508 GSM1479509 GSM1479510 GSM1479511 GSM1479512 GSM1479513 GSM1479514 GSM1479515 GSM1479516 GSM1479517 GSM1479518 GSM1479519 GSM1479520 GSM1479521 GSM1479522 GSM1479523 GSM1479524 GSM1479525 GSM1479526 GSM1479527 GSM1479528 GSM1479529 GSM1479530 GSM1479531 GSM1479532 GSM1479533 GSM1479534 GSM1479535 GSM1479536 GSM1479537 GSM1479538 GSM1479539 GSM1479540 GSM1479541 GSM1479542 GSM1479543 GSM1479544 GSM1479545 GSM1479546 GSM1479547 GSM1479548 GSM1479549 GSM1479550 GSM1479551 GSM1479552 GSM1479553 GSM1479554 GSM1479555 GSM1479556 GSM1479557 GSM1479558 GSM1479559 GSM1479560 GSM1479561 GSM1479562 GSM1479563 GSM1479564 GSM1479565 GSM1479566 "
23: !Series_contact_name	"Stephanie,,Osmond"
24: !Series_contact_email	"sosmond@benaroyaresearch.org"
25: !Series_contact_institute	"Benaroya Research Institute"
26: !Series_contact_address	"1201 9th Ave"
27: !Series_contact_city	"Seattle,"
28: !Series_contact_state	"WA"
29: !Series_contact_zip/postal_code	"98101"
30: !Series_contact_country	"USA"
31: !Series_supplementary_file	"ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE60nnn/GSE60424/suppl/GSE60424_GEOSubmit_FC1to11_normalized_counts.txt.gz"
32: !Series_platform_id	"GPL15456"
33: !Series_platform_taxid	"9606"
34: !Series_sample_taxid	"9606"
35: !Series_relation	"BioProject: https://www.ncbi.nlm.nih.gov/bioproject/PRJNA258216"
36: !Series_relation	"SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRP045500"
37:
38: !Sample_title	"lib221"	"lib222"	"lib223"	"lib224"	"lib225"	"lib226"	"lib227"	"lib228"	"lib229"	"lib230"	"lib231"	"lib232"	"lib233"	"lib234"	"lib235"	"lib236"	"lib237"	"lib238"	"lib239"	"lib240"	"lib241"	"lib242"	"lib243"	"lib244"	"lib245"	"lib246"	"lib247"	"lib248"	"lib249"	"lib250"	"lib251"	"lib252"	"lib253"	"lib254"	"lib255"	"lib256"	"lib257"	"lib258"	"lib259"	"lib260"	"lib261"	"lib262"	"lib263"	"lib264"	"lib265"	"lib266"	"lib267"	"lib268"	"lib269"	"lib270"	"lib271"	"lib272"	"lib273"	"lib274"	"lib275"	"lib276"	"lib277"	"lib278"	"lib279"	"lib280"	"lib281"	"lib282"	"lib283"	"lib284"	"lib285"	"lib286"	"lib288"	"lib289"	"lib290"	"lib291"	"lib292"	"lib293"	"lib294"	"lib295"	"lib296"	"lib297"	"lib298"	"lib299"	"lib300"	"lib301"	"lib302"	"lib303"	"lib304"	"lib305"	"lib306"	"lib307"	"lib308"	"lib309"	"lib310"	"lib311"	"lib312"	"lib313"	"lib314"	"lib315"	"lib316"	"lib317"	"lib318"	"lib319"	"lib320"	"lib321"	"lib322"	"lib323"	"lib324"	"lib325"	"lib326"	"lib327"	"lib328"	"lib329"	"lib330"	"lib331"	"lib332"	"lib333"	"lib334"	"lib335"	"lib336"	"lib337"	"lib338"	"lib339"	"lib340"	"lib341"	"lib342"	"lib343"	"lib344"	"lib345"	"lib346"	"lib347"	"lib348"	"lib349"	"lib350"	"lib351"	"lib352"	"lib353"	"lib354"	"lib355"
39: !Sample_geo_accession	"GSM1479433"	"GSM1479434"	"GSM1479435"	"GSM1479436"	"GSM1479437"	"GSM1479438"	"GSM1479439"	"GSM1479440"	"GSM1479441"	"GSM1479442"	"GSM1479443"	"GSM1479444"	"GSM1479445"	"GSM1479446"	"GSM1479447"	"GSM1479448"	"GSM1479449"	"GSM1479450"	"GSM1479451"	"GSM1479452"	"GSM1479453"	"GSM1479454"	"GSM1479455"	"GSM1479456"	"GSM1479457"	"GSM1479458"	"GSM1479459"	"GSM1479460"	"GSM1479461"	"GSM1479462"	"GSM1479463"	"GSM1479464"	"GSM1479465"	"GSM1479466"	"GSM1479467"	"GSM1479468"	"GSM1479469"	"GSM1479470"	"GSM1479471"	"GSM1479472"	"GSM1479473"	"GSM1479474"	"GSM1479475"	"GSM1479476"	"GSM1479477"	"GSM1479478"	"GSM1479479"	"GSM1479480"	"GSM1479481"	"GSM1479482"	"GSM1479483"	"GSM1479484"	"GSM1479485"	"GSM1479486"	"GSM1479487"	"GSM1479488"	"GSM1479489"	"GSM1479490"	"GSM1479491"	"GSM1479492"	"GSM1479493"	"GSM1479494"	"GSM1479495"	"GSM1479496"	"GSM1479497"	"GSM1479498"	"GSM1479499"	"GSM1479500"	"GSM1479501"	"GSM1479502"	"GSM1479503"	"GSM1479504"	"GSM1479505"	"GSM1479506"	"GSM1479507"	"GSM1479508"	"GSM1479509"	"GSM1479510"	"GSM1479511"	"GSM1479512"	"GSM1479513"	"GSM1479514"	"GSM1479515"	"GSM1479516"	"GSM1479517"	"GSM1479518"	"GSM1479519"	"GSM1479520"	"GSM1479521"	"GSM1479522"	"GSM1479523"	"GSM1479524"	"GSM1479525"	"GSM1479526"	"GSM1479527"	"GSM1479528"	"GSM1479529"	"GSM1479530"	"GSM1479531"	"GSM1479532"	"GSM1479533"	"GSM1479534"	"GSM1479535"	"GSM1479536"	"GSM1479537"	"GSM1479538"	"GSM1479539"	"GSM1479540"	"GSM1479541"	"GSM1479542"	"GSM1479543"	"GSM1479544"	"GSM1479545"	"GSM1479546"	"GSM1479547"	"GSM1479548"	"GSM1479549"	"GSM1479550"	"GSM1479551"	"GSM1479552"	"GSM1479553"	"GSM1479554"	"GSM1479555"	"GSM1479556"	"GSM1479557"	"GSM1479558"	"GSM1479559"	"GSM1479560"	"GSM1479561"	"GSM1479562"	"GSM1479563"	"GSM1479564"	"GSM1479565"	"GSM1479566"
40: !Sample_status	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"	"Public on Jan 06 2015"
41: !Sample_submission_date	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"	"Aug 14 2014"
42: !Sample_last_update_date	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"	"Jan 04 2024"
43: !Sample_type	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"	"SRA"
44: !Sample_channel_count	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"	"1"
45: !Sample_source_name_ch1	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"	"Whole Blood"
46: !Sample_organism_ch1	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"	"Homo sapiens"

In [4]:
sample_info = []

with open("../data/metadata/GSE60424_series_matrix.txt", "r", encoding="utf-8") as f:
    for line in f:
        if line.startswith("!Sample"):
            sample_info.append(line.strip().split("\t"))

sample_df = pd.DataFrame(sample_info)

sample_df.head()

,0,1,2,3,4,5,6,7,8,9,...,125,126,127,128,129,130,131,132,133,134
0,!Sample_title,"""lib221""","""lib222""","""lib223""","""lib224""","""lib225""","""lib226""","""lib227""","""lib228""","""lib229""",...,"""lib346""","""lib347""","""lib348""","""lib349""","""lib350""","""lib351""","""lib352""","""lib353""","""lib354""","""lib355"""
1,!Sample_geo_accession,"""GSM1479433""","""GSM1479434""","""GSM1479435""","""GSM1479436""","""GSM1479437""","""GSM1479438""","""GSM1479439""","""GSM1479440""","""GSM1479441""",...,"""GSM1479557""","""GSM1479558""","""GSM1479559""","""GSM1479560""","""GSM1479561""","""GSM1479562""","""GSM1479563""","""GSM1479564""","""GSM1479565""","""GSM1479566"""
2,!Sample_status,"""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""",...,"""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015"""
3,!Sample_submission_date,"""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""",...,"""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014"""
4,!Sample_last_update_date,"""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""",...,"""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024"""

In [5]:
sample_df.to_csv(
    "../data/processed/sample_metadata.csv",
    index=False
)

In [6]:
sample_df

,0,1,2,3,4,5,6,7,8,9,...,125,126,127,128,129,130,131,132,133,134
0,!Sample_title,"""lib221""","""lib222""","""lib223""","""lib224""","""lib225""","""lib226""","""lib227""","""lib228""","""lib229""",...,"""lib346""","""lib347""","""lib348""","""lib349""","""lib350""","""lib351""","""lib352""","""lib353""","""lib354""","""lib355"""
1,!Sample_geo_accession,"""GSM1479433""","""GSM1479434""","""GSM1479435""","""GSM1479436""","""GSM1479437""","""GSM1479438""","""GSM1479439""","""GSM1479440""","""GSM1479441""",...,"""GSM1479557""","""GSM1479558""","""GSM1479559""","""GSM1479560""","""GSM1479561""","""GSM1479562""","""GSM1479563""","""GSM1479564""","""GSM1479565""","""GSM1479566"""
2,!Sample_status,"""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""",...,"""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015""","""Public on Jan 06 2015"""
3,!Sample_submission_date,"""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""",...,"""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014""","""Aug 14 2014"""
4,!Sample_last_update_date,"""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""",...,"""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024""","""Jan 04 2024"""
5,!Sample_type,"""SRA""","""SRA""","""SRA""","""SRA""","""SRA""","""SRA""","""SRA""","""SRA""","""SRA""",...,"""SRA""","""SRA""","""SRA""","""SRA""","""SRA""","""SRA""","""SRA""","""SRA""","""SRA""","""SRA"""
6,!Sample_channel_count,"""1""","""1""","""1""","""1""","""1""","""1""","""1""","""1""","""1""",...,"""1""","""1""","""1""","""1""","""1""","""1""","""1""","""1""","""1""","""1"""
7,!Sample_source_name_ch1,"""Whole Blood""","""Whole Blood""","""Whole Blood""","""Whole Blood""","""Whole Blood""","""Whole Blood""","""Whole Blood""","""Whole Blood""","""Whole Blood""",...,"""Whole Blood""","""Whole Blood""","""Whole Blood""","""Whole Blood""","""Whole Blood""","""Whole Blood""","""Whole Blood""","""Whole Blood""","""Whole Blood""","""Whole Blood"""
8,!Sample_organism_ch1,"""Homo sapiens""","""Homo sapiens""","""Homo sapiens""","""Homo sapiens""","""Homo sapiens""","""Homo sapiens""","""Homo sapiens""","""Homo sapiens""","""Homo sapiens""",...,"""Homo sapiens""","""Homo sapiens""","""Homo sapiens""","""Homo sapiens""","""Homo sapiens""","""Homo sapiens""","""Homo sapiens""","""Homo sapiens""","""Homo sapiens""","""Homo sapiens"""
9,!Sample_characteristics_ch1,"""age: 32""","""age: 52""","""age: 52""","""age: 24""","""age: 27""","""age: 32""","""age: 32""","""age: 32""","""age: 32""",...,"""age: 35""","""age: 35""","""age: 35""","""age: --""","""age: --""","""age: --""","""age: --""","""age: --""","""age: --""","""age: --"""
10,!Sample_characteristics_ch1,"""cellcount: --""","""cellcount: --""","""cellcount: --""","""cellcount: --""","""cellcount: --""","""cellcount: 14737500""","""cellcount: 2000000""","""cellcount: 1012333""","""cellcount: 1071990""",...,"""cellcount: 1352936""","""cellcount: 310438""","""cellcount: --""","""cellcount: 12375000""","""cellcount: 2000000""","""cellcount: 2000000""","""cellcount: 2000000""","""cellcount: 2000000""","""cellcount: 1708523""","""cellcount: --"""
11,!Sample_characteristics_ch1,"""celltype: Whole Blood""","""celltype: Whole Blood""","""celltype: Whole Blood""","""celltype: Whole Blood""","""celltype: Whole Blood""","""celltype: Neutrophils""","""celltype: Monocytes""","""celltype: B-cells""","""celltype: CD4""",...,"""celltype: CD8""","""celltype: NK""","""celltype: Whole Blood""","""celltype: Neutrophils""","""celltype: Monocytes""","""celltype: B-cells""","""celltype: CD4""","""celltype: CD8""","""celltype: NK""","""celltype: Whole Blood"""
12,!Sample_characteristics_ch1,"""collectiondate: June 26 2012""","""collectiondate: May 21 2012""","""collectiondate: May 22 2012""","""collectiondate: May 23 2012""","""collectiondate: June 6 2012""","""collectiondate: June 26 2012""","""collectiondate: June 26 2012""","""collectiondate: June 26 2012""","""collectiondate: June 26 2012""",...,"""collectiondate: August 24 2012""","""collectiondate: August 24 2012""","""collectiondate: August 24 2012""","""collectiondate: September 12 2012""","""collectiondate: September 12 2012""","""collectiondate: September 12 2012""","""collectiondate: September 12 2012""","""collectiondate: September 12 2012""","""collectiondate: September 12 2012""","""collectiondate: September 12 2012"""
13,!Sample_characteristics_ch1,"""diseasestatus: Healthy Control""","""diseasestatus: MS pretreatment""","""diseasestatus: MS posttreatment""","""diseasestatus: Type 1 Diabetes""","""diseasestatus: Type 1 Diabetes""","""diseasestatus: Healthy Control""","""diseasestatus: Healthy Control""","""diseasestatus: Healthy Control""","""diseasestatus: Healthy Control""",...,"""diseasestatus: MS posttreatment""","""diseasestatus: MS posttreatment""","""diseasestatus: MS posttreatment""","""diseasestatus: ALS""","""diseasestatus: ALS""","""diseasestatus: ALS""","""diseasestatus: ALS""","""diseasestatus: ALS""","""diseasestatus: ALS""","""diseasestatus: ALS"""
14,!Sample_characteristics_ch1,"""donorid: 44""","""donorid: 31""","""donorid: 33""","""donorid: 34""","""donorid: 37""","""donorid: 44""","""donorid: 44""","""donorid: 44""","""donorid: 44""",...,"""donorid: 56""","""donorid: 56""","""donorid: 56""","""donorid: 58""","""donorid: 58""","""donorid: 58""","""donorid: 58""","""donorid: 58""","""donorid: 58""","""donorid: 58"""
15,!Sample_characteristics_ch1,"""gender: F""","""gender: F""","""gender: F""","""gender: F""","""gender: F""","""gender: F""","""gender: F""","""gender: F""","""gender: F""",...,"""gender: F""","""gender: F""","""gender: F""","""gender: ""","""gender: ""","""gender: ""","""gender: ""","""gender: ""","""gender: ""","""gender: """
16,!Sample_characteristics_ch1,"""index: 21""","""index: 2""","""index: 9""","""index: 13""","""index: 23""","""index: 5""","""index: 23""","""index: 6""","""index: 25""",...,"""index: 23""","""index: 9""","""index: 19""","""index: 12""","""index: 8""","""index: 11""","""index: 5""","""index: 20""","""index: 25""","""index: 10"""
17,!Sample_characteristics_ch1,"""race: Hispanic""","""race: White""","""race: White""","""race: White""","""race: White""","""race: Hispanic""","""race: Hispanic""","""race: Hispanic""","""race: Hispanic""",...,"""race: White""","""race: White""","""race: White""","""race: --""","""race: --""","""race: --""","""race: --""","""race: --""","""race: --""","""race: --"""
18,!Sample_characteristics_ch1,"""samplename: 44_Tempus""","""samplename: 31_Tempus""","""samplename: 33_Tempus""","""samplename: 34_Tempus""","""samplename: 37_Tempus""","""samplename: 44_Neutrophils""","""samplename: 44_Monocytes""","""samplename: 44_Bcells""","""samplename: 44_CD4T""",...,"""samplename: 56_CD8T""","""samplename: 56_NK""","""samplename: 56_Tempus""","""samplename: 58_Neutrophils""","""samplename: 58_Monocytes""","""samplename: 58_Bcells""","""samplename: 58_CD4T""","""samplename: 58_CD8T""","""samplename: 58_NK""","""samplename: 58_Tempus"""
19,!Sample_characteristics_ch1,"""smoker: --""","""smoker: Y""","""smoker: Y""","""smoker: --""","""smoker: --""","""smoker: --""","""smoker: --""","""smoker: --""","""smoker: --""",...,"""smoker: N""","""smoker: N""","""smoker: N""","""smoker: --""","""smoker: --""","""smoker: --""","""smoker: --""","""smoker: --""","""smoker: --""","""smoker: --"""
20,!Sample_characteristics_ch1,"""time since last flare (months): --""","""time since last flare (months): 1""","""time since last flare (months): 1""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""",...,"""time since last flare (months): 1""","""time since last flare (months): 1""","""time since last flare (months): 1""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --"""
21,!Sample_characteristics_ch1,"""time since steroid dose: --""","""time since steroid dose: 3 weeks, oral""","""time since steroid dose: 3 weeks, oral""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""",...,"""time since steroid dose: 1 month, IV""","""time since steroid dose: 1 month, IV""","""time since steroid dose: 1 month, IV""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --"""
22,!Sample_characteristics_ch1,"""time since symptom onset (yrs): --""","""time since symptom onset (yrs): 1""","""time since symptom onset (yrs): 1""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""",...,"""time since symptom onset (yrs): 0.5""","""time since symptom onset (yrs): 0.5""","""time since symptom onset (yrs): 0.5""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --"""
23,!Sample_characteristics_ch1,"""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: 7""","""years since diagnosis: 3""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""",...,"""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --"""
24,!Sample_molecule_ch1,"""total RNA""","""total RNA""","""total RNA""","""total RNA""","""total RNA""","""total RNA""","""total RNA""","""total RNA""","""total RNA""",...,"""total RNA""","""total RNA""","""total RNA""","""total RNA""","""total RNA""","""total RNA""","""total RNA""","""total RNA""","""total RNA""","""total RNA"""
25,!Sample_extract_protocol_ch1,"""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...",...,"""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt...","""Fresh blood samples were collected from healt..."
26,!Sample_taxid_ch1,"""9606""","""9606""","""9606""","""9606""","""9606""","""9606""","""9606""","""9606""","""9606""",...,"""9606""","""9606""","""9606""","""9606""","""9606""","""9606""","""9606""","""9606""","""9606""","""9606"""
27,!Sample_data_processing,"""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...",...,"""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ...","""fastq files were created from .bcl files via ..."
28,!Sample_data_processing,"""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...",...,"""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque...","""reads were aligned to Hg19 via Omicsoft seque..."
29,!Sample_data_processing,"""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...",...,"""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0...","""gene counts were generated by HTSeq version 0..."
30,!Sample_data_processing,"""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...",...,"""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package...","""TMMs were generated with Bioconductor package..."
31,!Sample_data_processing,"""Genome_build: Hg19""","""Genome_build: Hg19""","""Genome_build: Hg19""","""Genome_build: Hg19""","""Genome_build: Hg19""","""Genome_build: Hg19""","""Genome_build: Hg19""","""Genome_build: Hg19""","""Genome_build: Hg19""",...,"""Genome_build: Hg19""","""Genome_build: Hg19""","""Genome_build: Hg19""","""Genome_build: Hg19""","""Genome_build: Hg19""","""Genome_build: Hg19""","""Genome_build: Hg19""","""Genome_build: Hg19""","""Genome_build: Hg19""","""Genome_build: Hg19"""
32,!Sample_data_processing,"""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...",...,"""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d...","""Supplementary_files_format_and_content: tab d..."
33,!Sample_platform_id,"""GPL15456""","""GPL15456""","""GPL15456""","""GPL15456""","""GPL15456""","""GPL15456""","""GPL15456""","""GPL15456""","""GPL15456""",...,"""GPL15456""","""GPL15456""","""GPL15456""","""GPL15456""","""GPL15456""","""GPL15456""","""GPL15456""","""GPL15456""","""GPL15456""","""GPL15456"""
34,!Sample_contact_name,"""Stephanie,,Osmond""","""Stephanie,,Osmond""","""Stephanie,,Osmond""","""Stephanie,,Osmond""","""Stephanie,,Osmond""","""Stephanie,,Osmond""","""Stephanie,,Osmond""","""Stephanie,,Osmond""","""Stephanie,,Osmond""",...,"""Stephanie,,Osmond""","""Stephanie,,Osmond""","""Stephanie,,Osmond""","""Stephanie,,Osmond""","""Stephanie,,Osmond""","""Stephanie,,Osmond""","""Stephanie,,Osmond""","""Stephanie,,Osmond""","""Stephanie,,Osmond""","""Stephanie,,Osmond"""
35,!Sample_contact_email,"""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""",...,"""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org""","""sosmond@benaroyaresearch.org"""

In [7]:
sample_df[0].unique()

<StringArray>
[                  '!Sample_title',           '!Sample_geo_accession',
                  '!Sample_status',         '!Sample_submission_date',
        '!Sample_last_update_date',                    '!Sample_type',
           '!Sample_channel_count',         '!Sample_source_name_ch1',
            '!Sample_organism_ch1',     '!Sample_characteristics_ch1',
            '!Sample_molecule_ch1',    '!Sample_extract_protocol_ch1',
               '!Sample_taxid_ch1',         '!Sample_data_processing',
             '!Sample_platform_id',            '!Sample_contact_name',
           '!Sample_contact_email',       '!Sample_contact_institute',
         '!Sample_contact_address',            '!Sample_contact_city',
           '!Sample_contact_state', '!Sample_contact_zip/postal_code',
         '!Sample_contact_country',          '!Sample_data_row_count',
        '!Sample_instrument_model',       '!Sample_library_selection',
          '!Sample_library_source',        '!Sample_library_strategy',
                '!Sample_relation',    '!Sample_supplementary_file_1']
Length: 30, dtype: str

In [8]:
sample_df[sample_df[0] == "!Sample_characteristics_ch1"]

,0,1,2,3,4,5,6,7,8,9,...,125,126,127,128,129,130,131,132,133,134
9,!Sample_characteristics_ch1,"""age: 32""","""age: 52""","""age: 52""","""age: 24""","""age: 27""","""age: 32""","""age: 32""","""age: 32""","""age: 32""",...,"""age: 35""","""age: 35""","""age: 35""","""age: --""","""age: --""","""age: --""","""age: --""","""age: --""","""age: --""","""age: --"""
10,!Sample_characteristics_ch1,"""cellcount: --""","""cellcount: --""","""cellcount: --""","""cellcount: --""","""cellcount: --""","""cellcount: 14737500""","""cellcount: 2000000""","""cellcount: 1012333""","""cellcount: 1071990""",...,"""cellcount: 1352936""","""cellcount: 310438""","""cellcount: --""","""cellcount: 12375000""","""cellcount: 2000000""","""cellcount: 2000000""","""cellcount: 2000000""","""cellcount: 2000000""","""cellcount: 1708523""","""cellcount: --"""
11,!Sample_characteristics_ch1,"""celltype: Whole Blood""","""celltype: Whole Blood""","""celltype: Whole Blood""","""celltype: Whole Blood""","""celltype: Whole Blood""","""celltype: Neutrophils""","""celltype: Monocytes""","""celltype: B-cells""","""celltype: CD4""",...,"""celltype: CD8""","""celltype: NK""","""celltype: Whole Blood""","""celltype: Neutrophils""","""celltype: Monocytes""","""celltype: B-cells""","""celltype: CD4""","""celltype: CD8""","""celltype: NK""","""celltype: Whole Blood"""
12,!Sample_characteristics_ch1,"""collectiondate: June 26 2012""","""collectiondate: May 21 2012""","""collectiondate: May 22 2012""","""collectiondate: May 23 2012""","""collectiondate: June 6 2012""","""collectiondate: June 26 2012""","""collectiondate: June 26 2012""","""collectiondate: June 26 2012""","""collectiondate: June 26 2012""",...,"""collectiondate: August 24 2012""","""collectiondate: August 24 2012""","""collectiondate: August 24 2012""","""collectiondate: September 12 2012""","""collectiondate: September 12 2012""","""collectiondate: September 12 2012""","""collectiondate: September 12 2012""","""collectiondate: September 12 2012""","""collectiondate: September 12 2012""","""collectiondate: September 12 2012"""
13,!Sample_characteristics_ch1,"""diseasestatus: Healthy Control""","""diseasestatus: MS pretreatment""","""diseasestatus: MS posttreatment""","""diseasestatus: Type 1 Diabetes""","""diseasestatus: Type 1 Diabetes""","""diseasestatus: Healthy Control""","""diseasestatus: Healthy Control""","""diseasestatus: Healthy Control""","""diseasestatus: Healthy Control""",...,"""diseasestatus: MS posttreatment""","""diseasestatus: MS posttreatment""","""diseasestatus: MS posttreatment""","""diseasestatus: ALS""","""diseasestatus: ALS""","""diseasestatus: ALS""","""diseasestatus: ALS""","""diseasestatus: ALS""","""diseasestatus: ALS""","""diseasestatus: ALS"""
14,!Sample_characteristics_ch1,"""donorid: 44""","""donorid: 31""","""donorid: 33""","""donorid: 34""","""donorid: 37""","""donorid: 44""","""donorid: 44""","""donorid: 44""","""donorid: 44""",...,"""donorid: 56""","""donorid: 56""","""donorid: 56""","""donorid: 58""","""donorid: 58""","""donorid: 58""","""donorid: 58""","""donorid: 58""","""donorid: 58""","""donorid: 58"""
15,!Sample_characteristics_ch1,"""gender: F""","""gender: F""","""gender: F""","""gender: F""","""gender: F""","""gender: F""","""gender: F""","""gender: F""","""gender: F""",...,"""gender: F""","""gender: F""","""gender: F""","""gender: ""","""gender: ""","""gender: ""","""gender: ""","""gender: ""","""gender: ""","""gender: """
16,!Sample_characteristics_ch1,"""index: 21""","""index: 2""","""index: 9""","""index: 13""","""index: 23""","""index: 5""","""index: 23""","""index: 6""","""index: 25""",...,"""index: 23""","""index: 9""","""index: 19""","""index: 12""","""index: 8""","""index: 11""","""index: 5""","""index: 20""","""index: 25""","""index: 10"""
17,!Sample_characteristics_ch1,"""race: Hispanic""","""race: White""","""race: White""","""race: White""","""race: White""","""race: Hispanic""","""race: Hispanic""","""race: Hispanic""","""race: Hispanic""",...,"""race: White""","""race: White""","""race: White""","""race: --""","""race: --""","""race: --""","""race: --""","""race: --""","""race: --""","""race: --"""
18,!Sample_characteristics_ch1,"""samplename: 44_Tempus""","""samplename: 31_Tempus""","""samplename: 33_Tempus""","""samplename: 34_Tempus""","""samplename: 37_Tempus""","""samplename: 44_Neutrophils""","""samplename: 44_Monocytes""","""samplename: 44_Bcells""","""samplename: 44_CD4T""",...,"""samplename: 56_CD8T""","""samplename: 56_NK""","""samplename: 56_Tempus""","""samplename: 58_Neutrophils""","""samplename: 58_Monocytes""","""samplename: 58_Bcells""","""samplename: 58_CD4T""","""samplename: 58_CD8T""","""samplename: 58_NK""","""samplename: 58_Tempus"""
19,!Sample_characteristics_ch1,"""smoker: --""","""smoker: Y""","""smoker: Y""","""smoker: --""","""smoker: --""","""smoker: --""","""smoker: --""","""smoker: --""","""smoker: --""",...,"""smoker: N""","""smoker: N""","""smoker: N""","""smoker: --""","""smoker: --""","""smoker: --""","""smoker: --""","""smoker: --""","""smoker: --""","""smoker: --"""
20,!Sample_characteristics_ch1,"""time since last flare (months): --""","""time since last flare (months): 1""","""time since last flare (months): 1""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""",...,"""time since last flare (months): 1""","""time since last flare (months): 1""","""time since last flare (months): 1""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --""","""time since last flare (months): --"""
21,!Sample_characteristics_ch1,"""time since steroid dose: --""","""time since steroid dose: 3 weeks, oral""","""time since steroid dose: 3 weeks, oral""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""",...,"""time since steroid dose: 1 month, IV""","""time since steroid dose: 1 month, IV""","""time since steroid dose: 1 month, IV""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --""","""time since steroid dose: --"""
22,!Sample_characteristics_ch1,"""time since symptom onset (yrs): --""","""time since symptom onset (yrs): 1""","""time since symptom onset (yrs): 1""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""",...,"""time since symptom onset (yrs): 0.5""","""time since symptom onset (yrs): 0.5""","""time since symptom onset (yrs): 0.5""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --""","""time since symptom onset (yrs): --"""
23,!Sample_characteristics_ch1,"""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: 7""","""years since diagnosis: 3""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""",...,"""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --""","""years since diagnosis: --"""

In [9]:
metadata2 = sample_df.set_index(0).T
metadata2.head()

,!Sample_title,!Sample_geo_accession,!Sample_status,!Sample_submission_date,!Sample_last_update_date,!Sample_type,!Sample_channel_count,!Sample_source_name_ch1,!Sample_organism_ch1,!Sample_characteristics_ch1,...,!Sample_contact_zip/postal_code,!Sample_contact_country,!Sample_data_row_count,!Sample_instrument_model,!Sample_library_selection,!Sample_library_source,!Sample_library_strategy,!Sample_relation,!Sample_relation,!Sample_supplementary_file_1
1,"""lib221""","""GSM1479433""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: 32""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
2,"""lib222""","""GSM1479434""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: 52""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
3,"""lib223""","""GSM1479435""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: 52""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
4,"""lib224""","""GSM1479436""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: 24""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
5,"""lib225""","""GSM1479437""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: 27""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""

In [ ]:
import pandas as pd

# 1. Create a list for the brand new column names
new_headers = []

for col in metadata2.columns:
    # Look at the first data row (index 1) to find the type prefix
    # e.g., '"age: 32"'
    first_val = str(metadata2[col].iloc[1])
    
    if ":" in first_val:
        # Split by the colon, take the left side, and clean up quotes/spaces
        # '"age: 32"' becomes 'age'
        clean_header = first_val.split(":")[0].replace('"', '').strip()
        new_headers.append(clean_header)
    else:
        # If there's no colon (like an ID column), keep its original name or row 0 name
        fallback = str(metadata2[col].iloc[0]).replace('"', '').strip()
        new_headers.append(fallback if fallback else col)

# 2. Clean the data cells: Remove the "prefix: " part and outer quotes from all rows
for col in metadata2.columns:
    # Remove everything up to the first colon
    # 1. Create a list for the brand new column names
    new_headers = []

    for col in metadata2.columns:
        # Look at the first data row (index 1) to find the type prefix
        # e.g., '"age: 32"'
        first_val = str(metadata2[col].iloc[1])
        
        if ":" in first_val:
            # Split by the colon, take the left side, and clean up quotes/spaces
            # '"age: 32"' becomes 'age'
            clean_header = first_val.split(":")[0].replace('"', '').strip()
            new_headers.append(clean_header)
        else:
            # If there's no colon (like an ID column), keep its original name or row 0 name
            fallback = str(metadata2[col].iloc[0]).replace('"', '').strip()
            new_headers.append(fallback if fallback else col)

    # 2. Clean the data cells: Remove the "prefix: " part and outer quotes from all rows
    for col in metadata2.columns:
        # Remove everything up to the first colon (safer using apply to avoid .str on DataFrame)
        metadata2[col] = metadata2[col].astype(str).apply(lambda x: x.split(":", 1)[-1] if ":" in x else x)
        # Strip any remaining double quotes and whitespaces
        metadata2[col] = metadata2[col].str.replace('"', '', regex=False).str.strip()

    # 3. Assign the beautifully extracted headers directly to the dataframe
    metadata2.columns = new_headers

    # 4. Drop the original row 0 since it just contains the old "!Sample..." tags
    metadata2 = metadata2.iloc[1:].reset_index(drop=True)

    # Check the result
    # metadata2 = pd.DataFrame(metadata2).T  # Ensure it's a DataFrame in case of any type issues
    print(metadata2.head())
    # Strip any remaining double quotes and whitespaces
    metadata2[col] = metadata2[col].str.replace('"', '', regex=False).str.strip()

# 3. Assign the beautifully extracted headers directly to the dataframe
metadata2.columns = new_headers

# 4. Drop the original row 0 since it just contains the old "!Sample..." tags
metadata2 = metadata2.iloc[1:].reset_index(drop=True)

# Check the result
# metadata2 = pd.DataFrame(metadata2).T  # Ensure it's a DataFrame in case of any type issues
print(metadata2.head())

AttributeError: 'DataFrame' object has no attribute 'str'

In [11]:
metadata2

,!Sample_title,lib221,lib222,lib223,lib224,lib225,lib226,lib227,lib228,lib229,...,lib346,lib347,lib348,lib349,lib350,lib351,lib352,lib353,lib354,lib355
0,!Sample_geo_accession,GSM1479433,GSM1479434,GSM1479435,GSM1479436,GSM1479437,GSM1479438,GSM1479439,GSM1479440,GSM1479441,...,GSM1479557,GSM1479558,GSM1479559,GSM1479560,GSM1479561,GSM1479562,GSM1479563,GSM1479564,GSM1479565,GSM1479566
1,!Sample_status,Public on Jan 06 2015,Public on Jan 06 2015,Public on Jan 06 2015,Public on Jan 06 2015,Public on Jan 06 2015,Public on Jan 06 2015,Public on Jan 06 2015,Public on Jan 06 2015,Public on Jan 06 2015,...,Public on Jan 06 2015,Public on Jan 06 2015,Public on Jan 06 2015,Public on Jan 06 2015,Public on Jan 06 2015,Public on Jan 06 2015,Public on Jan 06 2015,Public on Jan 06 2015,Public on Jan 06 2015,Public on Jan 06 2015
2,!Sample_submission_date,Aug 14 2014,Aug 14 2014,Aug 14 2014,Aug 14 2014,Aug 14 2014,Aug 14 2014,Aug 14 2014,Aug 14 2014,Aug 14 2014,...,Aug 14 2014,Aug 14 2014,Aug 14 2014,Aug 14 2014,Aug 14 2014,Aug 14 2014,Aug 14 2014,Aug 14 2014,Aug 14 2014,Aug 14 2014
3,!Sample_last_update_date,Jan 04 2024,Jan 04 2024,Jan 04 2024,Jan 04 2024,Jan 04 2024,Jan 04 2024,Jan 04 2024,Jan 04 2024,Jan 04 2024,...,Jan 04 2024,Jan 04 2024,Jan 04 2024,Jan 04 2024,Jan 04 2024,Jan 04 2024,Jan 04 2024,Jan 04 2024,Jan 04 2024,Jan 04 2024
4,!Sample_type,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA,...,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA
5,!Sample_channel_count,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
6,!Sample_source_name_ch1,Whole Blood,Whole Blood,Whole Blood,Whole Blood,Whole Blood,Whole Blood,Whole Blood,Whole Blood,Whole Blood,...,Whole Blood,Whole Blood,Whole Blood,Whole Blood,Whole Blood,Whole Blood,Whole Blood,Whole Blood,Whole Blood,Whole Blood
7,!Sample_organism_ch1,Homo sapiens,Homo sapiens,Homo sapiens,Homo sapiens,Homo sapiens,Homo sapiens,Homo sapiens,Homo sapiens,Homo sapiens,...,Homo sapiens,Homo sapiens,Homo sapiens,Homo sapiens,Homo sapiens,Homo sapiens,Homo sapiens,Homo sapiens,Homo sapiens,Homo sapiens
8,!Sample_characteristics_ch1,32,52,52,24,27,32,32,32,32,...,35,35,35,--,--,--,--,--,--,--
9,!Sample_characteristics_ch1,--,--,--,--,--,14737500,2000000,1012333,1071990,...,1352936,310438,--,12375000,2000000,2000000,2000000,2000000,1708523,--
10,!Sample_characteristics_ch1,Whole Blood,Whole Blood,Whole Blood,Whole Blood,Whole Blood,Neutrophils,Monocytes,B-cells,CD4,...,CD8,NK,Whole Blood,Neutrophils,Monocytes,B-cells,CD4,CD8,NK,Whole Blood
11,!Sample_characteristics_ch1,June 26 2012,May 21 2012,May 22 2012,May 23 2012,June 6 2012,June 26 2012,June 26 2012,June 26 2012,June 26 2012,...,August 24 2012,August 24 2012,August 24 2012,September 12 2012,September 12 2012,September 12 2012,September 12 2012,September 12 2012,September 12 2012,September 12 2012
12,!Sample_characteristics_ch1,Healthy Control,MS pretreatment,MS posttreatment,Type 1 Diabetes,Type 1 Diabetes,Healthy Control,Healthy Control,Healthy Control,Healthy Control,...,MS posttreatment,MS posttreatment,MS posttreatment,ALS,ALS,ALS,ALS,ALS,ALS,ALS
13,!Sample_characteristics_ch1,44,31,33,34,37,44,44,44,44,...,56,56,56,58,58,58,58,58,58,58
14,!Sample_characteristics_ch1,F,F,F,F,F,F,F,F,F,...,F,F,F,,,,,,,
15,!Sample_characteristics_ch1,21,2,9,13,23,5,23,6,25,...,23,9,19,12,8,11,5,20,25,10
16,!Sample_characteristics_ch1,Hispanic,White,White,White,White,Hispanic,Hispanic,Hispanic,Hispanic,...,White,White,White,--,--,--,--,--,--,--
17,!Sample_characteristics_ch1,44_Tempus,31_Tempus,33_Tempus,34_Tempus,37_Tempus,44_Neutrophils,44_Monocytes,44_Bcells,44_CD4T,...,56_CD8T,56_NK,56_Tempus,58_Neutrophils,58_Monocytes,58_Bcells,58_CD4T,58_CD8T,58_NK,58_Tempus
18,!Sample_characteristics_ch1,--,Y,Y,--,--,--,--,--,--,...,N,N,N,--,--,--,--,--,--,--
19,!Sample_characteristics_ch1,--,1,1,--,--,--,--,--,--,...,1,1,1,--,--,--,--,--,--,--
20,!Sample_characteristics_ch1,--,"3 weeks, oral","3 weeks, oral",--,--,--,--,--,--,...,"1 month, IV","1 month, IV","1 month, IV",--,--,--,--,--,--,--
21,!Sample_characteristics_ch1,--,1,1,--,--,--,--,--,--,...,0.5,0.5,0.5,--,--,--,--,--,--,--
22,!Sample_characteristics_ch1,--,--,--,7,3,--,--,--,--,...,--,--,--,--,--,--,--,--,--,--
23,!Sample_molecule_ch1,total RNA,total RNA,total RNA,total RNA,total RNA,total RNA,total RNA,total RNA,total RNA,...,total RNA,total RNA,total RNA,total RNA,total RNA,total RNA,total RNA,total RNA,total RNA,total RNA
24,!Sample_extract_protocol_ch1,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...,Fresh blood samples were collected from health...
25,!Sample_taxid_ch1,9606,9606,9606,9606,9606,9606,9606,9606,9606,...,9606,9606,9606,9606,9606,9606,9606,9606,9606,9606
26,!Sample_data_processing,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...,fastq files were created from .bcl files via I...
27,!Sample_data_processing,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...,reads were aligned to Hg19 via Omicsoft sequen...
28,!Sample_data_processing,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,...,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....,gene counts were generated by HTSeq version 0....
29,!Sample_data_processing,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...,TMMs were generated with Bioconductor package ...
30,!Sample_data_processing,Hg19,Hg19,Hg19,Hg19,Hg19,Hg19,Hg19,Hg19,Hg19,...,Hg19,Hg19,Hg19,Hg19,Hg19,Hg19,Hg19,Hg19,Hg19,Hg19
31,!Sample_data_processing,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,...,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts,tab delimited file contains TMM normalized counts
32,!Sample_platform_id,GPL15456,GPL15456,GPL15456,GPL15456,GPL15456,GPL15456,GPL15456,GPL15456,GPL15456,...,GPL15456,GPL15456,GPL15456,GPL15456,GPL15456,GPL15456,GPL15456,GPL15456,GPL15456,GPL15456
33,!Sample_contact_name,"Stephanie,,Osmond","Stephanie,,Osmond","Stephanie,,Osmond","Stephanie,,Osmond","Stephanie,,Osmond","Stephanie,,Osmond","Stephanie,,Osmond","Stephanie,,Osmond","Stephanie,,Osmond",...,"Stephanie,,Osmond","Stephanie,,Osmond","Stephanie,,Osmond","Stephanie,,Osmond","Stephanie,,Osmond","Stephanie,,Osmond","Stephanie,,Osmond","Stephanie,,Osmond","Stephanie,,Osmond","Stephanie,,Osmond"
34,!Sample_contact_email,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,...,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org,sosmond@benaroyaresearch.org
35,!Sample_contact_institute,Benaroya Research Institute,Benaroya Research Institute,Benaroya Research Institute,Benaroya Research Institute,Benaroya Research Institute,Benaroya Research Institute,Benaroya Research Institute,Benaroya Research Institute,Benaroya Research Institute,...,Benaroya Research Institute,Benaroya Research Institute,Benaroya Research Institute,Benaroya Research Institute,Benaroya Research Institute,Benaroya Research Institute,Benaroya Research Institute,Benaroya Research Institute,Benaroya Research Institute,Benaroya Research Institute
36,!Sample_contact_address,1201 9th Ave,1201 9th Ave,1201 9th Ave,1201 9th Ave,1201 9th Ave,1201 9th Ave,1201 9th Ave,1201 9th Ave,1201 9th Ave,...,1201 9th Ave,1201 9th Ave,1201 9th Ave,1201 9th Ave,1201 9th Ave,1201 9th Ave,1201 9th Ave,1201 9th Ave,1201 9th Ave,1201 9th Ave
37,!Sample_contact_city,"Seattle,","Seattle,","Seattle,","Seattle,","Seattle,","Seattle,","Seattle,","Seattle,","Seattle,",...,"Seattle,","Seattle,","Seattle,","Seattle,","Seattle,","Seattle,","Seattle,","Seattle,","Seattle,","Seattle,"
38,!Sample_contact_state,WA,WA,WA,WA,WA,WA,WA,WA,WA,...,WA,WA,WA,WA,WA,WA,WA,WA,WA,WA
39,!Sample_contact_zip/postal_code,98101,98101,98101,98101,98101,98101,98101,98101,98101,...,98101,98101,98101,98101,98101,98101,98101,98101,98101,98101
40,!Sample_contact_country,USA,USA,USA,USA,USA,USA,USA,USA,USA,...,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA
41,!Sample_data_row_count,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,!Sample_instrument_model,Illumina HiScanSQ,Illumina HiScanSQ,Illumina HiScanSQ,Illumina HiScanSQ,Illumina HiScanSQ,Illumina HiScanSQ,Illumina HiScanSQ,Illumina HiScanSQ,Illumina HiScanSQ,...,Illumina HiScanSQ,Illumina HiScanSQ,Illumina HiScanSQ,Illumina HiScanSQ,Illumina HiScanSQ,Illumina HiScanSQ,Illumina HiScanSQ,Illumina HiScanSQ,Illumina HiScanSQ,Illumina HiScanSQ
43,!Sample_library_selection,cDNA,cDNA,cDNA,cDNA,cDNA,cDNA,cDNA,cDNA,cDNA,...,cDNA,cDNA,cDNA,cDNA,cDNA,cDNA,cDNA,cDNA,cDNA,cDNA
44,!Sample_library_source,transcriptomic,transcriptomic,transcriptomic,transcriptomic,transcriptomic,transcriptomic,transcriptomic,transcriptomic,transcriptomic,...,transcriptomic,transcriptomic,transcriptomic,transcriptomic,transcriptomic,transcriptomic,transcriptomic,transcriptomic,transcriptomic,transcriptomic
45,!Sample_library_strategy,RNA-Seq,RNA-Seq,RNA-Seq,RNA-Seq,RNA-Seq,RNA-Seq,RNA-Seq,RNA-Seq,RNA-Seq,...,RNA-Seq,RNA-Seq,RNA-Seq,RNA-Seq,RNA-Seq,RNA-Seq,RNA-Seq,RNA-Seq,RNA-Seq,RNA-Seq
46,!Sample_relation,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...
47,!Sample_relation,https://www.ncbi.nlm.nih.gov/sra?term=SRX680541,https://www.ncbi.nlm.nih.gov/sra?term=SRX680542,https://www.ncbi.nlm.nih.gov/sra?term=SRX680543,https://www.ncbi.nlm.nih.gov/sra?term=SRX680544,https://www.ncbi.nlm.nih.gov/sra?term=SRX680545,https://www.ncbi.nlm.nih.gov/sra?term=SRX680546,https://www.ncbi.nlm.nih.gov/sra?term=SRX680547,https://www.ncbi.nlm.nih.gov/sra?term=SRX680548,https://www.ncbi.nlm.nih.gov/sra?term=SRX680549,...,https://www.ncbi.nlm.nih.gov/sra?term=SRX680665,https://www.ncbi.nlm.nih.gov/sra?term=SRX680666,https://www.ncbi.nlm.nih.gov/sra?term=SRX680667,https://www.ncbi.nlm.nih.gov/sra?term=SRX680668,https://www.ncbi.nlm.nih.gov/sra?term=SRX680669,https://www.ncbi.nlm.nih.gov/sra?term=SRX680670,https://www.ncbi.nlm.nih.gov/sra?term=SRX680671,https://www.ncbi.nlm.nih.gov/sra?term=SRX680672,https://www.ncbi.nlm.nih.gov/sra?term=SRX680673,https://www.ncbi.nlm.nih.gov/sra?term=SRX680674
48,!Sample_supplementary_file_1,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE