In [1]:
import pandas as pd

In [2]:
metadata = pd.read_csv('../data/processed/sample_metadata.csv'
                       )

In [3]:
metadata1 = metadata.T

In [4]:
metadata1

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,!Sample_title,!Sample_geo_accession,!Sample_status,!Sample_submission_date,!Sample_last_update_date,!Sample_type,!Sample_channel_count,!Sample_source_name_ch1,!Sample_organism_ch1,!Sample_characteristics_ch1,...,!Sample_contact_zip/postal_code,!Sample_contact_country,!Sample_data_row_count,!Sample_instrument_model,!Sample_library_selection,!Sample_library_source,!Sample_library_strategy,!Sample_relation,!Sample_relation,!Sample_supplementary_file_1
1,"""lib221""","""GSM1479433""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: 32""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
2,"""lib222""","""GSM1479434""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: 52""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
3,"""lib223""","""GSM1479435""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: 52""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
4,"""lib224""","""GSM1479436""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: 24""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,"""lib351""","""GSM1479562""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: --""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
131,"""lib352""","""GSM1479563""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: --""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
132,"""lib353""","""GSM1479564""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: --""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
133,"""lib354""","""GSM1479565""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: --""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
134,"""lib355""","""GSM1479566""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: --""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""

In [5]:
metadata1.iloc[0,:]

0                       !Sample_title
1               !Sample_geo_accession
2                      !Sample_status
3             !Sample_submission_date
4            !Sample_last_update_date
5                        !Sample_type
6               !Sample_channel_count
7             !Sample_source_name_ch1
8                !Sample_organism_ch1
9         !Sample_characteristics_ch1
10        !Sample_characteristics_ch1
11        !Sample_characteristics_ch1
12        !Sample_characteristics_ch1
13        !Sample_characteristics_ch1
14        !Sample_characteristics_ch1
15        !Sample_characteristics_ch1
16        !Sample_characteristics_ch1
17        !Sample_characteristics_ch1
18        !Sample_characteristics_ch1
19        !Sample_characteristics_ch1
20        !Sample_characteristics_ch1
21        !Sample_characteristics_ch1
22        !Sample_characteristics_ch1
23        !Sample_characteristics_ch1
24               !Sample_molecule_ch1
25       !Sample_extract_protocol_ch1
26                  !Sample_taxid_ch1
27            !Sample_data_processing
28            !Sample_data_processing
29            !Sample_data_processing
30            !Sample_data_processing
31            !Sample_data_processing
32            !Sample_data_processing
33                !Sample_platform_id
34               !Sample_contact_name
35              !Sample_contact_email
36          !Sample_contact_institute
37            !Sample_contact_address
38               !Sample_contact_city
39              !Sample_contact_state
40    !Sample_contact_zip/postal_code
41            !Sample_contact_country
42             !Sample_data_row_count
43           !Sample_instrument_model
44          !Sample_library_selection
45             !Sample_library_source
46           !Sample_library_strategy
47                   !Sample_relation
48                   !Sample_relation
49       !Sample_supplementary_file_1
Name: 0, dtype: str

In [16]:
metadata1

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,!Sample_title,!Sample_geo_accession,!Sample_status,!Sample_submission_date,!Sample_last_update_date,!Sample_type,!Sample_channel_count,!Sample_source_name_ch1,!Sample_organism_ch1,!Sample_characteristics_ch1,...,!Sample_contact_zip/postal_code,!Sample_contact_country,!Sample_data_row_count,!Sample_instrument_model,!Sample_library_selection,!Sample_library_source,!Sample_library_strategy,!Sample_relation,!Sample_relation,!Sample_supplementary_file_1
1,"""lib221""","""GSM1479433""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: 32""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
2,"""lib222""","""GSM1479434""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: 52""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
3,"""lib223""","""GSM1479435""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: 52""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
4,"""lib224""","""GSM1479436""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: 24""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,"""lib351""","""GSM1479562""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: --""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
131,"""lib352""","""GSM1479563""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: --""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
132,"""lib353""","""GSM1479564""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: --""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
133,"""lib354""","""GSM1479565""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: --""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""
134,"""lib355""","""GSM1479566""","""Public on Jan 06 2015""","""Aug 14 2014""","""Jan 04 2024""","""SRA""","""1""","""Whole Blood""","""Homo sapiens""","""age: --""",...,"""98101""","""USA""","""0""","""Illumina HiScanSQ""","""cDNA""","""transcriptomic""","""RNA-Seq""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR...","""NONE"""

In [17]:
metadata1.iloc[:,2].value_counts

<bound method IndexOpsMixin.value_counts of 0               !Sample_status
1      "Public on Jan 06 2015"
2      "Public on Jan 06 2015"
3      "Public on Jan 06 2015"
4      "Public on Jan 06 2015"
                ...
130    "Public on Jan 06 2015"
131    "Public on Jan 06 2015"
132    "Public on Jan 06 2015"
133    "Public on Jan 06 2015"
134    "Public on Jan 06 2015"
Name: 2, Length: 135, dtype: str>

In [18]:
metadata1.iloc[:,3].value_counts

<bound method IndexOpsMixin.value_counts of 0      !Sample_submission_date
1                "Aug 14 2014"
2                "Aug 14 2014"
3                "Aug 14 2014"
4                "Aug 14 2014"
                ...
130              "Aug 14 2014"
131              "Aug 14 2014"
132              "Aug 14 2014"
133              "Aug 14 2014"
134              "Aug 14 2014"
Name: 3, Length: 135, dtype: str>

In [19]:
metadata1.iloc[:,4].value_counts

<bound method IndexOpsMixin.value_counts of 0      !Sample_last_update_date
1                 "Jan 04 2024"
2                 "Jan 04 2024"
3                 "Jan 04 2024"
4                 "Jan 04 2024"
                 ...
130               "Jan 04 2024"
131               "Jan 04 2024"
132               "Jan 04 2024"
133               "Jan 04 2024"
134               "Jan 04 2024"
Name: 4, Length: 135, dtype: str>

In [20]:
metadata1.iloc[:,5].value_counts

<bound method IndexOpsMixin.value_counts of 0      !Sample_type
1             "SRA"
2             "SRA"
3             "SRA"
4             "SRA"
           ...
130           "SRA"
131           "SRA"
132           "SRA"
133           "SRA"
134           "SRA"
Name: 5, Length: 135, dtype: str>

In [21]:
metadata1.iloc[:,6].value_counts

<bound method IndexOpsMixin.value_counts of 0      !Sample_channel_count
1                        "1"
2                        "1"
3                        "1"
4                        "1"
               ...
130                      "1"
131                      "1"
132                      "1"
133                      "1"
134                      "1"
Name: 6, Length: 135, dtype: str>

In [22]:
metadata1.iloc[:,7].value_counts

<bound method IndexOpsMixin.value_counts of 0      !Sample_source_name_ch1
1                "Whole Blood"
2                "Whole Blood"
3                "Whole Blood"
4                "Whole Blood"
                ...
130              "Whole Blood"
131              "Whole Blood"
132              "Whole Blood"
133              "Whole Blood"
134              "Whole Blood"
Name: 7, Length: 135, dtype: str>

In [23]:
metadata1.iloc[:,8].value_counts

<bound method IndexOpsMixin.value_counts of 0      !Sample_organism_ch1
1            "Homo sapiens"
2            "Homo sapiens"
3            "Homo sapiens"
4            "Homo sapiens"
               ...
130          "Homo sapiens"
131          "Homo sapiens"
132          "Homo sapiens"
133          "Homo sapiens"
134          "Homo sapiens"
Name: 8, Length: 135, dtype: str>

In [28]:
metadata1[9].unique()

<StringArray>
['!Sample_characteristics_ch1',                   '"age: 32"',
                   '"age: 52"',                   '"age: 24"',
                   '"age: 27"',                   '"age: 80"',
                   '"age: 39"',                   '"age: 59"',
                   '"age: 36"',                   '"age: 29"',
                   '"age: 22"',                   '"age: --"',
                   '"age: 30"',                   '"age: 42"',
                   '"age: 21"',                   '"age: 35"']
Length: 16, dtype: str

In [41]:
metadata1[10].unique()

<StringArray>
['!Sample_characteristics_ch1',             '"cellcount: --"',
       '"cellcount: 14737500"',        '"cellcount: 2000000"',
        '"cellcount: 1012333"',        '"cellcount: 1071990"',
        '"cellcount: 1011154"',         '"cellcount: 379236"',
       '"cellcount: 16312500"',         '"cellcount: 409387"',
        '"cellcount: 1100105"',      '"cellcount: 190000000"',
         '"cellcount: 273769"',       '"cellcount: 19800000"',
        '"cellcount: 1006332"',         '"cellcount: 320942"',
       '"cellcount: 10237500"',         '"cellcount: 903409"',
        '"cellcount: 1786114"',       '"cellcount: 45900000"',
          '"cellcount: 73307"',         '"cellcount: 953426"',
       '"cellcount: 31250000"',         '"cellcount: 498269"',
       '"cellcount: 49750000"',         '"cellcount: 529358"',
         '"cellcount: 365861"',       '"cellcount: 41000000"',
         '"cellcount: 843981"',         '"cellcount: 329348"',
       '"cellcount: 34537500"',         '"cellcount: 487967"',
         '"cellcount: 301460"',       '"cellcount: 42250000"',
        '"cellcount: 1500000"',         '"cellcount: 285000"',
        '"cellcount: 3700000"',         '"cellcount: 363469"',
         '"cellcount: 147461"',        '"cellcount: 7987500"',
         '"cellcount: 702000"',         '"cellcount: 928859"',
         '"cellcount: 552072"',       '"cellcount: 17887500"',
         '"cellcount: 682371"',         '"cellcount: 140773"',
       '"cellcount: 15862500"',        '"cellcount: 1078502"',
         '"cellcount: 601013"',       '"cellcount: 17550000"',
        '"cellcount: 1275892"',        '"cellcount: 1741969"',
       '"cellcount: 12825000"',         '"cellcount: 484043"',
        '"cellcount: 1719279"',         '"cellcount: 223256"',
       '"cellcount: 13275000"',         '"cellcount: 871287"',
         '"cellcount: 640619"',        '"cellcount: 1352936"',
         '"cellcount: 310438"',       '"cellcount: 12375000"',
        '"cellcount: 1708523"']
Length: 63, dtype: str

In [42]:
metadata1[11].unique()

<StringArray>
['!Sample_characteristics_ch1',     '"celltype: Whole Blood"',
     '"celltype: Neutrophils"',       '"celltype: Monocytes"',
         '"celltype: B-cells"',             '"celltype: CD4"',
             '"celltype: CD8"',              '"celltype: NK"']
Length: 8, dtype: str

In [43]:
metadata1[12].unique()

<StringArray>
[        '!Sample_characteristics_ch1',      '"collectiondate: June 26 2012"',
       '"collectiondate: May 21 2012"',       '"collectiondate: May 22 2012"',
       '"collectiondate: May 23 2012"',       '"collectiondate: June 6 2012"',
      '"collectiondate: June 22 2012"',       '"collectiondate: July 5 2012"',
       '"collectiondate: July 6 2012"',      '"collectiondate: June 28 2012"',
      '"collectiondate: June 29 2012"',   '"collectiondate: January 25 2012"',
   '"collectiondate: February 2 2012"',    '"collectiondate: August 16 2012"',
    '"collectiondate: August 21 2012"',    '"collectiondate: August 22 2012"',
      '"collectiondate: June 19 2012"',      '"collectiondate: June 20 2012"',
    '"collectiondate: August 23 2012"',    '"collectiondate: August 24 2012"',
 '"collectiondate: September 12 2012"']
Length: 21, dtype: str

In [44]:
metadata1[13].unique()

<StringArray>
[      '!Sample_characteristics_ch1',  '"diseasestatus: Healthy Control"',
  '"diseasestatus: MS pretreatment"', '"diseasestatus: MS posttreatment"',
  '"diseasestatus: Type 1 Diabetes"',           '"diseasestatus: Sepsis"',
              '"diseasestatus: ALS"']
Length: 7, dtype: str

In [45]:
metadata1[14].unique()

<StringArray>
['!Sample_characteristics_ch1',               '"donorid: 44"',
               '"donorid: 31"',               '"donorid: 33"',
               '"donorid: 34"',               '"donorid: 37"',
               '"donorid: 43"',               '"donorid: 49"',
               '"donorid: 50"',               '"donorid: 45"',
               '"donorid: 46"',               '"donorid: 20"',
               '"donorid: 21"',               '"donorid: 52"',
               '"donorid: 53"',               '"donorid: 54"',
               '"donorid: 40"',               '"donorid: 41"',
               '"donorid: 55"',               '"donorid: 56"',
               '"donorid: 58"']
Length: 21, dtype: str

In [46]:
metadata1[15].unique()

<StringArray>
['!Sample_characteristics_ch1', '"gender: F"', '"gender: M"', '"gender: "']
Length: 4, dtype: str

In [47]:
metadata1[16].unique()

<StringArray>
['!Sample_characteristics_ch1',                 '"index: 21"',
                  '"index: 2"',                  '"index: 9"',
                 '"index: 13"',                 '"index: 23"',
                  '"index: 5"',                  '"index: 6"',
                 '"index: 25"',                 '"index: 12"',
                 '"index: 19"',                  '"index: 1"',
                  '"index: 4"',                  '"index: 3"',
                  '"index: 8"',                 '"index: 10"',
                  '"index: 7"',                 '"index: 11"',
                 '"index: 20"',                 '"index: 14"',
                 '"index: 15"',                 '"index: 22"',
                 '"index: 16"',                 '"index: 18"',
                 '"index: 27"']
Length: 25, dtype: str

In [48]:
metadata1[16].unique()

<StringArray>
['!Sample_characteristics_ch1',                 '"index: 21"',
                  '"index: 2"',                  '"index: 9"',
                 '"index: 13"',                 '"index: 23"',
                  '"index: 5"',                  '"index: 6"',
                 '"index: 25"',                 '"index: 12"',
                 '"index: 19"',                  '"index: 1"',
                  '"index: 4"',                  '"index: 3"',
                  '"index: 8"',                 '"index: 10"',
                  '"index: 7"',                 '"index: 11"',
                 '"index: 20"',                 '"index: 14"',
                 '"index: 15"',                 '"index: 22"',
                 '"index: 16"',                 '"index: 18"',
                 '"index: 27"']
Length: 25, dtype: str

In [49]:
metadata1[17].unique()

<StringArray>
['!Sample_characteristics_ch1',            '"race: Hispanic"',
               '"race: White"',               '"race: Asian"',
                  '"race: --"']
Length: 5, dtype: str

In [50]:
metadata1[18].unique()

<StringArray>
[ '!Sample_characteristics_ch1',      '"samplename: 44_Tempus"',
      '"samplename: 31_Tempus"',      '"samplename: 33_Tempus"',
      '"samplename: 34_Tempus"',      '"samplename: 37_Tempus"',
 '"samplename: 44_Neutrophils"',   '"samplename: 44_Monocytes"',
      '"samplename: 44_Bcells"',        '"samplename: 44_CD4T"',
 ...
        '"samplename: 56_CD8T"',          '"samplename: 56_NK"',
      '"samplename: 56_Tempus"', '"samplename: 58_Neutrophils"',
   '"samplename: 58_Monocytes"',      '"samplename: 58_Bcells"',
        '"samplename: 58_CD4T"',        '"samplename: 58_CD8T"',
          '"samplename: 58_NK"',      '"samplename: 58_Tempus"']
Length: 135, dtype: str

In [51]:
metadata1[19].unique()

<StringArray>
['!Sample_characteristics_ch1', '"smoker: --"', '"smoker: Y"', '"smoker: N"']
Length: 4, dtype: str

In [52]:
metadata1[20].unique()

<StringArray>
[         '!Sample_characteristics_ch1',
 '"time since last flare (months): --"',
  '"time since last flare (months): 1"',
 '"time since last flare (months): 47"']
Length: 4, dtype: str

In [53]:
metadata1[21].unique()

<StringArray>
[             '!Sample_characteristics_ch1',
            '"time since steroid dose: --"',
 '"time since steroid dose: 3 weeks, oral"',
   '"time since steroid dose: 1 month, IV"']
Length: 4, dtype: str

In [54]:
metadata1[22].unique()

<StringArray>
[          '!Sample_characteristics_ch1',
  '"time since symptom onset (yrs): --"',
   '"time since symptom onset (yrs): 1"',
  '"time since symptom onset (yrs): 10"',
 '"time since symptom onset (yrs): 0.5"']
Length: 5, dtype: str

In [55]:
metadata1[23].unique()

<StringArray>
[ '!Sample_characteristics_ch1',  '"years since diagnosis: --"',
   '"years since diagnosis: 7"',   '"years since diagnosis: 3"',
   '"years since diagnosis: 6"', '"years since diagnosis: 2.5"']
Length: 6, dtype: str

In [60]:
metadata1[24].unique()

<StringArray>
['!Sample_molecule_ch1', '"total RNA"']
Length: 2, dtype: str

In [61]:
metadata1[25].unique()

<StringArray>
['!Sample_extract_protocol_ch1', '"Fresh blood samples were collected from healthy subjects and subjects diagnosed type 1 diabetes, amyotrophic lateral sclerosis, and sepsis, as well as multiple sclerosis patients before and 24 hours after the first treatment with IFN-beta. At the time of blood draw, an aliquot of whole blood was collected into a Tempus tube (Invitrogen), while the remainder of the primary fresh blood sample was processed to highly pure populations of neutrophils, monocytes, B cells, CD4 T cells, CD8 T cells, and natural killer cells. RNA was extracted from each of these cell subsets, as well as the whole blood samples, and processed into RNA sequencing (RNAseq) libraries (Illumina TruSeq). Sequencing libraries were analyzed on an Illumina HiScan, with a target read depth of ~20M reads. Reads were demultiplexed, mapped to human gene models (ENSEMBL), and tabulated using HTSeq. Read count data were normalized by the TMM procedure (edgeR package)."']
Length: 2, dtype: str

In [62]:
metadata1[26].unique()

<StringArray>
['!Sample_taxid_ch1', '"9606"']
Length: 2, dtype: str

In [7]:
x = []

for i in metadata1.columns:
    if metadata1[i].nunique() > 2:
        # print(f"Column {i} has {metadata1[i].nunique()} unique values: {metadata1[i].unique()}")
        x.append(metadata1[i])

x= pd.DataFrame(x).T
x

,0,1,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,47,48
0,!Sample_title,!Sample_geo_accession,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_relation,!Sample_relation
1,"""lib221""","""GSM1479433""","""age: 32""","""cellcount: --""","""celltype: Whole Blood""","""collectiondate: June 26 2012""","""diseasestatus: Healthy Control""","""donorid: 44""","""gender: F""","""index: 21""","""race: Hispanic""","""samplename: 44_Tempus""","""smoker: --""","""time since last flare (months): --""","""time since steroid dose: --""","""time since symptom onset (yrs): --""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
2,"""lib222""","""GSM1479434""","""age: 52""","""cellcount: --""","""celltype: Whole Blood""","""collectiondate: May 21 2012""","""diseasestatus: MS pretreatment""","""donorid: 31""","""gender: F""","""index: 2""","""race: White""","""samplename: 31_Tempus""","""smoker: Y""","""time since last flare (months): 1""","""time since steroid dose: 3 weeks, oral""","""time since symptom onset (yrs): 1""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
3,"""lib223""","""GSM1479435""","""age: 52""","""cellcount: --""","""celltype: Whole Blood""","""collectiondate: May 22 2012""","""diseasestatus: MS posttreatment""","""donorid: 33""","""gender: F""","""index: 9""","""race: White""","""samplename: 33_Tempus""","""smoker: Y""","""time since last flare (months): 1""","""time since steroid dose: 3 weeks, oral""","""time since symptom onset (yrs): 1""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
4,"""lib224""","""GSM1479436""","""age: 24""","""cellcount: --""","""celltype: Whole Blood""","""collectiondate: May 23 2012""","""diseasestatus: Type 1 Diabetes""","""donorid: 34""","""gender: F""","""index: 13""","""race: White""","""samplename: 34_Tempus""","""smoker: --""","""time since last flare (months): --""","""time since steroid dose: --""","""time since symptom onset (yrs): --""","""years since diagnosis: 7""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,"""lib351""","""GSM1479562""","""age: --""","""cellcount: 2000000""","""celltype: B-cells""","""collectiondate: September 12 2012""","""diseasestatus: ALS""","""donorid: 58""","""gender: ""","""index: 11""","""race: --""","""samplename: 58_Bcells""","""smoker: --""","""time since last flare (months): --""","""time since steroid dose: --""","""time since symptom onset (yrs): --""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
131,"""lib352""","""GSM1479563""","""age: --""","""cellcount: 2000000""","""celltype: CD4""","""collectiondate: September 12 2012""","""diseasestatus: ALS""","""donorid: 58""","""gender: ""","""index: 5""","""race: --""","""samplename: 58_CD4T""","""smoker: --""","""time since last flare (months): --""","""time since steroid dose: --""","""time since symptom onset (yrs): --""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
132,"""lib353""","""GSM1479564""","""age: --""","""cellcount: 2000000""","""celltype: CD8""","""collectiondate: September 12 2012""","""diseasestatus: ALS""","""donorid: 58""","""gender: ""","""index: 20""","""race: --""","""samplename: 58_CD8T""","""smoker: --""","""time since last flare (months): --""","""time since steroid dose: --""","""time since symptom onset (yrs): --""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
133,"""lib354""","""GSM1479565""","""age: --""","""cellcount: 1708523""","""celltype: NK""","""collectiondate: September 12 2012""","""diseasestatus: ALS""","""donorid: 58""","""gender: ""","""index: 25""","""race: --""","""samplename: 58_NK""","""smoker: --""","""time since last flare (months): --""","""time since steroid dose: --""","""time since symptom onset (yrs): --""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
134,"""lib355""","""GSM1479566""","""age: --""","""cellcount: --""","""celltype: Whole Blood""","""collectiondate: September 12 2012""","""diseasestatus: ALS""","""donorid: 58""","""gender: ""","""index: 10""","""race: --""","""samplename: 58_Tempus""","""smoker: --""","""time since last flare (months): --""","""time since steroid dose: --""","""time since symptom onset (yrs): --""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."

In [14]:
metadata2 = metadata1.drop(columns=[col for col in metadata1.columns if metadata1[col].nunique() <= 2])
metadata2

,0,1,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,47,48
0,!Sample_title,!Sample_geo_accession,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_characteristics_ch1,!Sample_relation,!Sample_relation
1,"""lib221""","""GSM1479433""","""age: 32""","""cellcount: --""","""celltype: Whole Blood""","""collectiondate: June 26 2012""","""diseasestatus: Healthy Control""","""donorid: 44""","""gender: F""","""index: 21""","""race: Hispanic""","""samplename: 44_Tempus""","""smoker: --""","""time since last flare (months): --""","""time since steroid dose: --""","""time since symptom onset (yrs): --""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
2,"""lib222""","""GSM1479434""","""age: 52""","""cellcount: --""","""celltype: Whole Blood""","""collectiondate: May 21 2012""","""diseasestatus: MS pretreatment""","""donorid: 31""","""gender: F""","""index: 2""","""race: White""","""samplename: 31_Tempus""","""smoker: Y""","""time since last flare (months): 1""","""time since steroid dose: 3 weeks, oral""","""time since symptom onset (yrs): 1""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
3,"""lib223""","""GSM1479435""","""age: 52""","""cellcount: --""","""celltype: Whole Blood""","""collectiondate: May 22 2012""","""diseasestatus: MS posttreatment""","""donorid: 33""","""gender: F""","""index: 9""","""race: White""","""samplename: 33_Tempus""","""smoker: Y""","""time since last flare (months): 1""","""time since steroid dose: 3 weeks, oral""","""time since symptom onset (yrs): 1""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
4,"""lib224""","""GSM1479436""","""age: 24""","""cellcount: --""","""celltype: Whole Blood""","""collectiondate: May 23 2012""","""diseasestatus: Type 1 Diabetes""","""donorid: 34""","""gender: F""","""index: 13""","""race: White""","""samplename: 34_Tempus""","""smoker: --""","""time since last flare (months): --""","""time since steroid dose: --""","""time since symptom onset (yrs): --""","""years since diagnosis: 7""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,"""lib351""","""GSM1479562""","""age: --""","""cellcount: 2000000""","""celltype: B-cells""","""collectiondate: September 12 2012""","""diseasestatus: ALS""","""donorid: 58""","""gender: ""","""index: 11""","""race: --""","""samplename: 58_Bcells""","""smoker: --""","""time since last flare (months): --""","""time since steroid dose: --""","""time since symptom onset (yrs): --""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
131,"""lib352""","""GSM1479563""","""age: --""","""cellcount: 2000000""","""celltype: CD4""","""collectiondate: September 12 2012""","""diseasestatus: ALS""","""donorid: 58""","""gender: ""","""index: 5""","""race: --""","""samplename: 58_CD4T""","""smoker: --""","""time since last flare (months): --""","""time since steroid dose: --""","""time since symptom onset (yrs): --""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
132,"""lib353""","""GSM1479564""","""age: --""","""cellcount: 2000000""","""celltype: CD8""","""collectiondate: September 12 2012""","""diseasestatus: ALS""","""donorid: 58""","""gender: ""","""index: 20""","""race: --""","""samplename: 58_CD8T""","""smoker: --""","""time since last flare (months): --""","""time since steroid dose: --""","""time since symptom onset (yrs): --""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
133,"""lib354""","""GSM1479565""","""age: --""","""cellcount: 1708523""","""celltype: NK""","""collectiondate: September 12 2012""","""diseasestatus: ALS""","""donorid: 58""","""gender: ""","""index: 25""","""race: --""","""samplename: 58_NK""","""smoker: --""","""time since last flare (months): --""","""time since steroid dose: --""","""time since symptom onset (yrs): --""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."
134,"""lib355""","""GSM1479566""","""age: --""","""cellcount: --""","""celltype: Whole Blood""","""collectiondate: September 12 2012""","""diseasestatus: ALS""","""donorid: 58""","""gender: ""","""index: 10""","""race: --""","""samplename: 58_Tempus""","""smoker: --""","""time since last flare (months): --""","""time since steroid dose: --""","""time since symptom onset (yrs): --""","""years since diagnosis: --""","""BioSample: https://www.ncbi.nlm.nih.gov/biosa...","""SRA: https://www.ncbi.nlm.nih.gov/sra?term=SR..."

In [15]:
import pandas as pd

# 1. Create a list for the brand new column names
new_headers = []

for col in metadata2.columns:
    # Look at the first data row (index 1) to find the type prefix
    # e.g., '"age: 32"'
    first_val = str(metadata2[col].iloc[1])
    
    if ":" in first_val:
        # Split by the colon, take the left side, and clean up quotes/spaces
        # '"age: 32"' becomes 'age'
        clean_header = first_val.split(":")[0].replace('"', '').strip()
        new_headers.append(clean_header)
    else:
        # If there's no colon (like an ID column), keep its original name or row 0 name
        fallback = str(metadata2[col].iloc[0]).replace('"', '').strip()
        new_headers.append(fallback if fallback else col)

# 2. Clean the data cells: Remove the "prefix: " part and outer quotes from all rows
for col in metadata2.columns:
    # Remove everything up to the first colon
    metadata2[col] = metadata2[col].astype(str).str.split(':', n=1).str[-1]
    # Strip any remaining double quotes and whitespaces
    metadata2[col] = metadata2[col].str.replace('"', '', regex=False).str.strip()

# 3. Assign the beautifully extracted headers directly to the dataframe
metadata2.columns = new_headers

# 4. Drop the original row 0 since it just contains the old "!Sample..." tags
metadata2 = metadata2.iloc[1:].reset_index(drop=True)

# Check the result
# metadata2 = pd.DataFrame(metadata2).T  # Ensure it's a DataFrame in case of any type issues
print(metadata2.head())

  !Sample_title !Sample_geo_accession age cellcount     celltype  \
0        lib221            GSM1479433  32        --  Whole Blood
1        lib222            GSM1479434  52        --  Whole Blood
2        lib223            GSM1479435  52        --  Whole Blood
3        lib224            GSM1479436  24        --  Whole Blood
4        lib225            GSM1479437  27        --  Whole Blood

  collectiondate     diseasestatus donorid gender index      race samplename  \
0   June 26 2012   Healthy Control      44      F    21  Hispanic  44_Tempus
1    May 21 2012   MS pretreatment      31      F     2     White  31_Tempus
2    May 22 2012  MS posttreatment      33      F     9     White  33_Tempus
3    May 23 2012   Type 1 Diabetes      34      F    13     White  34_Tempus
4    June 6 2012   Type 1 Diabetes      37      F    23     White  37_Tempus

  smoker time since last flare (months) time since steroid dose  \
0     --                             --                      --
1      Y                              1           3 weeks, oral
2      Y                              1           3 weeks, oral
3     --                             --                      --
4     --                             --                      --

  time since symptom onset (yrs) years since diagnosis  \
0                             --                    --
1                              1                    --
2                              1                    --
3                             --                     7
4                             --                     3

                                           BioSample  \
0  https://www.ncbi.nlm.nih.gov/biosample/SAMN029...
1  https://www.ncbi.nlm.nih.gov/biosample/SAMN029...
2  https://www.ncbi.nlm.nih.gov/biosample/SAMN029...
3  https://www.ncbi.nlm.nih.gov/biosample/SAMN029...
4  https://www.ncbi.nlm.nih.gov/biosample/SAMN029...

                                               SRA
0  https://www.ncbi.nlm.nih.gov/sra?term=SRX680541
1  https://www.ncbi.nlm.nih.gov/sra?term=SRX680542
2  https://www.ncbi.nlm.nih.gov/sra?term=SRX680543
3  https://www.ncbi.nlm.nih.gov/sra?term=SRX680544
4  https://www.ncbi.nlm.nih.gov/sra?term=SRX680545

In [77]:
metadata2 = meta

In [16]:
metadata2

,!Sample_title,!Sample_geo_accession,age,cellcount,celltype,collectiondate,diseasestatus,donorid,gender,index,race,samplename,smoker,time since last flare (months),time since steroid dose,time since symptom onset (yrs),years since diagnosis,BioSample,SRA
0,lib221,GSM1479433,32,--,Whole Blood,June 26 2012,Healthy Control,44,F,21,Hispanic,44_Tempus,--,--,--,--,--,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/sra?term=SRX680541
1,lib222,GSM1479434,52,--,Whole Blood,May 21 2012,MS pretreatment,31,F,2,White,31_Tempus,Y,1,"3 weeks, oral",1,--,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/sra?term=SRX680542
2,lib223,GSM1479435,52,--,Whole Blood,May 22 2012,MS posttreatment,33,F,9,White,33_Tempus,Y,1,"3 weeks, oral",1,--,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/sra?term=SRX680543
3,lib224,GSM1479436,24,--,Whole Blood,May 23 2012,Type 1 Diabetes,34,F,13,White,34_Tempus,--,--,--,--,7,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/sra?term=SRX680544
4,lib225,GSM1479437,27,--,Whole Blood,June 6 2012,Type 1 Diabetes,37,F,23,White,37_Tempus,--,--,--,--,3,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/sra?term=SRX680545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,lib351,GSM1479562,--,2000000,B-cells,September 12 2012,ALS,58,,11,--,58_Bcells,--,--,--,--,--,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/sra?term=SRX680670
130,lib352,GSM1479563,--,2000000,CD4,September 12 2012,ALS,58,,5,--,58_CD4T,--,--,--,--,--,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/sra?term=SRX680671
131,lib353,GSM1479564,--,2000000,CD8,September 12 2012,ALS,58,,20,--,58_CD8T,--,--,--,--,--,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/sra?term=SRX680672
132,lib354,GSM1479565,--,1708523,NK,September 12 2012,ALS,58,,25,--,58_NK,--,--,--,--,--,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/sra?term=SRX680673
133,lib355,GSM1479566,--,--,Whole Blood,September 12 2012,ALS,58,,10,--,58_Tempus,--,--,--,--,--,https://www.ncbi.nlm.nih.gov/biosample/SAMN029...,https://www.ncbi.nlm.nih.gov/sra?term=SRX680674

In [ ]:
metadata2.isnull().sum()

!Sample_title                     0
!Sample_geo_accession             0
age                               0
cellcount                         0
celltype                          0
collectiondate                    0
diseasestatus                     0
donorid                           0
gender                            0
index                             0
race                              0
samplename                        0
smoker                            0
time since last flare (months)    0
time since steroid dose           0
time since symptom onset (yrs)    0
years since diagnosis             0
BioSample                         0
SRA                               0
dtype: int64

In [22]:
metadata2.eq('--' or '  ').sum()

!Sample_title                       0
!Sample_geo_accession               0
age                                21
cellcount                          20
celltype                            0
collectiondate                      0
diseasestatus                       0
donorid                             0
gender                              0
index                               0
race                               21
samplename                          0
smoker                             95
time since last flare (months)     95
time since steroid dose           109
time since symptom onset (yrs)     95
years since diagnosis             108
BioSample                           0
SRA                                 0
dtype: int64

In [20]:
metadata2['gender'].value_counts()

gender
F    100
      21
M     13
Name: count, dtype: int64